const countriesData = {
  "languages": [
    { code: "en", label: "English" },
    { code: "fr", label: "Français" },
    { code: "es", label: "Español" },
    { code: "de", label: "Deutsch(German)" },
    { code: "it", label: "Italiano" },
  ],

  "euroZone": [
      "AT",
      "BE",
      "CY",
      "EE",
      "FI",
      "FR",
      "DE",
      "HR",
      "GR",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MT",
      "NL",
      "PT",
      "SK",
      "SI",
      "ES",
  ],

  "currencies": [
    { code: "GBP", name: "British Pound Sterling", flag: "gb", symbol: "£" },
    { code: "USD", name: "United States Dollar", flag: "us", symbol: "$" },
    { code: "EUR", name: "Euro", flag: "eu", symbol: "€" },
    { code: "CHF", name: "Swiss Franc", flag: "ch", symbol: "CHF" },
    { code: "CAD", name: "Canadian Dollar", flag: "ca", symbol: "C$" },
    { code: "AUD", name: "Australian Dollar", flag: "au", symbol: "A$" },
    { code: "AED", name: "UAE Dirham", flag: "ae", symbol: "د.إ" },
    { code: "AFN", name: "Afghan Afghani", flag: "af", symbol: "؋" },
    { code: "ALL", name: "Albanian Lek", flag: "al", symbol: "L" },
    { code: "AMD", name: "Armenian Dram", flag: "am", symbol: "֏" },
    { code: "ANG", name: "Netherlands Antillean Guilder", flag: "cw", symbol: "ƒ" },
    { code: "AOA", name: "Angolan Kwanza", flag: "ao", symbol: "Kz" },
    { code: "ARS", name: "Argentine Peso", flag: "ar", symbol: "$" },
    { code: "AWG", name: "Aruban Florin", flag: "aw", symbol: "ƒ" },
    { code: "AZN", name: "Azerbaijani Manat", flag: "az", symbol: "₼" },
    { code: "BAM", name: "Bosnia-Herzegovina Marka", flag: "ba", symbol: "KM" },
    { code: "BBD", name: "Barbadian Dollar", flag: "bb", symbol: "$" },
    { code: "BDT", name: "Bangladeshi Taka", flag: "bd", symbol: "৳" },
    { code: "BGN", name: "Bulgarian Lev", flag: "bg", symbol: "лв" },
    { code: "BHD", name: "Bahraini Dinar", flag: "bh", symbol: ".د.ب" },
    { code: "BIF", name: "Burundian Franc", flag: "bi", symbol: "FBu" },
    { code: "BMD", name: "Bermudian Dollar", flag: "bm", symbol: "$" },
    { code: "BND", name: "Brunei Dollar", flag: "bn", symbol: "B$" },
    { code: "BOB", name: "Bolivian Boliviano", flag: "bo", symbol: "$b" },
    { code: "BRL", name: "Brazilian Real", flag: "br", symbol: "R$" },
    { code: "BSD", name: "Bahamian Dollar", flag: "bs", symbol: "$" },
    { code: "BTN", name: "Bhutanese Ngultrum", flag: "bt", symbol: "Nu." },
    { code: "BWP", name: "Botswanan Pula", flag: "bw", symbol: "P" },
    { code: "BYN", name: "New Belarusian Ruble", flag: "by", symbol: "Br" },
    { code: "BZD", name: "Belize Dollar", flag: "bz", symbol: "BZ$" },
    { code: "CDF", name: "Congolese Franc", flag: "cd", symbol: "FC" },
    { code: "CLP", name: "Chilean Peso", flag: "cl", symbol: "$" },
    { code: "CNY", name: "Chinese Yuan Renminbi", flag: "cn", symbol: "¥" },
    { code: "COP", name: "Colombian Peso", flag: "co", symbol: "$" },
    { code: "CRC", name: "Costa Rican Colon", flag: "cr", symbol: "₡" },
    { code: "CUP", name: "Cuban Peso", flag: "cu", symbol: "₱" },
    { code: "CVE", name: "Cape Verdean Escudo", flag: "cv", symbol: "$" },
    { code: "CZK", name: "Czech Koruna", flag: "cz", symbol: "Kč" },
    { code: "DJF", name: "Djibouti Franc", flag: "dj", symbol: "Fdj" },
    { code: "DKK", name: "Danish Krone", flag: "dk", symbol: "kr" },
    { code: "DOP", name: "Dominican Peso", flag: "do", symbol: "RD$" },
    { code: "DZD", name: "Algerian Dinar", flag: "dz", symbol: "دج" },
    { code: "EGP", name: "Egyptian Pound", flag: "eg", symbol: "£" },
    { code: "ERN", name: "Eritrean Nakfa", flag: "er", symbol: "Nfk" },
    { code: "ETB", name: "Ethiopian Birr", flag: "et", symbol: "Br" },
    { code: "FJD", name: "Fiji Dollar", flag: "fj", symbol: "$" },
    { code: "FKP", name: "Falkland Islands Pound", flag: "fk", symbol: "£" },
    { code: "GEL", name: "Georgian Lari", flag: "ge", symbol: "₾" },
    { code: "GHS", name: "Ghanaian Cedi", flag: "gh", symbol: "GH₵" },
    { code: "GIP", name: "Gibraltar Pound", flag: "gi", symbol: "£" },
    { code: "GMD", name: "Gambian Dalasi", flag: "gm", symbol: "D" },
    { code: "GNF", name: "Guinean Franc", flag: "gn", symbol: "FG" },
    { code: "GTQ", name: "Guatemalan Quetzal", flag: "gt", symbol: "Q" },
    { code: "GYD", name: "Guyana Dollar", flag: "gy", symbol: "$" },
    { code: "HKD", name: "Hong Kong Dollar", flag: "hk", symbol: "HK$" },
    { code: "HNL", name: "Honduran Lempira", flag: "hn", symbol: "L" },
    { code: "HTG", name: "Haitian Gourde", flag: "ht", symbol: "G" },
    { code: "HUF", name: "Hungarian Forint", flag: "hu", symbol: "Ft" },
    { code: "IDR", name: "Indonesian Rupiah", flag: "id", symbol: "Rp" },
    { code: "ILS", name: "New Israeli Sheqel", flag: "il", symbol: "₪" },
    { code: "INR", name: "Indian Rupee", flag: "in", symbol: "₹" },
    { code: "IQD", name: "Iraqi Dinar", flag: "iq", symbol: "ع.د" },
    { code: "IRR", name: "Iranian Rial", flag: "ir", symbol: "﷼" },
    { code: "ISK", name: "Iceland Krona", flag: "is", symbol: "kr" },
    { code: "JMD", name: "Jamaican Dollar", flag: "jm", symbol: "J$" },
    { code: "JOD", name: "Jordanian Dinar", flag: "jo", symbol: "JD" },
    { code: "JPY", name: "Japanese Yen", flag: "jp", symbol: "¥" },
    { code: "KES", name: "Kenyan Shilling", flag: "ke", symbol: "KSh" },
    { code: "KGS", name: "Kyrgyzstani Som", flag: "kg", symbol: "лв" },
    { code: "KHR", name: "Cambodian Riel", flag: "kh", symbol: "៛" },
    { code: "KMF", name: "Comorian Franc", flag: "km", symbol: "CF" },
    { code: "KRW", name: "South Korean Won", flag: "kr", symbol: "₩" },
    { code: "KWD", name: "Kuwaiti Dinar", flag: "kw", symbol: "KD" },
    { code: "KYD", name: "Cayman Islands Dollar", flag: "ky", symbol: "$" },
    { code: "KZT", name: "Kazakhstani Tenge", flag: "kz", symbol: "₸" },
    { code: "LAK", name: "Laotian Kip", flag: "la", symbol: "₭" },
    { code: "LBP", name: "Lebanese Pound", flag: "lb", symbol: "£" },
    { code: "LKR", name: "Sri Lankan Rupee", flag: "lk", symbol: "Rs" },
    { code: "LRD", name: "Liberian Dollar", flag: "lr", symbol: "$" },
    { code: "LSL", name: "Lesotho Loti", flag: "ls", symbol: "L" },
    { code: "LYD", name: "Libyan Dinar", flag: "ly", symbol: "LD" },
    { code: "MAD", name: "Moroccan Dirham", flag: "ma", symbol: "MAD" },
    { code: "MDL", name: "Moldovan Leu", flag: "md", symbol: "L" },
    { code: "MGA", name: "Malagasy Ariary", flag: "mg", symbol: "Ar" },
    { code: "MKD", name: "Macedonian Denar", flag: "mk", symbol: "ден" },
    { code: "MMK", name: "Burmese Kyat", flag: "mm", symbol: "K" },
    { code: "MNT", name: "Mongolian Tögrög", flag: "mn", symbol: "₮" },
    { code: "MOP", name: "Macau Pataca", flag: "mo", symbol: "MOP$" },
    { code: "MRU", name: "Mauritanian Ouguiya", flag: "mr", symbol: "UM" },
    { code: "MUR", name: "Mauritius Rupee", flag: "mu", symbol: "₨" },
    { code: "MVR", name: "Maldivian Rufiyaa", flag: "mv", symbol: "Rf" },
    { code: "MWK", name: "Malawian Kwacha", flag: "mw", symbol: "MK" },
    { code: "MXN", name: "Mexican Peso", flag: "mx", symbol: "$" },
    { code: "MYR", name: "Malaysian Ringgit", flag: "my", symbol: "RM" },
    { code: "MZN", name: "Mozambican Metical", flag: "mz", symbol: "MT" },
    { code: "NAD", name: "Namibian Dollar", flag: "na", symbol: "$" },
    { code: "NGN", name: "Nigerian Naira", flag: "ng", symbol: "₦" },
    { code: "NIO", name: "Nicaraguan Córdoba", flag: "ni", symbol: "C$" },
    { code: "NOK", name: "Norwegian Krone", flag: "no", symbol: "kr" },
    { code: "NPR", name: "Nepalese Rupee", flag: "np", symbol: "₨" },
    { code: "NZD", name: "New Zealand Dollar", flag: "nz", symbol: "NZ$" },
    { code: "OMR", name: "Omani Rial", flag: "om", symbol: "﷼" },
    { code: "PAB", name: "Panamanian Balboa", flag: "pa", symbol: "B/." },
    { code: "PEN", name: "Peruvian Sol", flag: "pe", symbol: "S/." },
    { code: "PGK", name: "Papua New Guinean Kina", flag: "pg", symbol: "K" },
    { code: "PHP", name: "Philippine Piso", flag: "ph", symbol: "₱" },
    { code: "PKR", name: "Pakistani Rupee", flag: "pk", symbol: "₨" },
    { code: "PLN", name: "Polish Zloty", flag: "pl", symbol: "zł" },
    { code: "PYG", name: "Paraguayan Guaraní", flag: "py", symbol: "Gs" },
    { code: "QAR", name: "Qatari Rial", flag: "qa", symbol: "﷼" },
    { code: "RON", name: "Romanian Leu", flag: "ro", symbol: "lei" },
    { code: "RSD", name: "Serbian Dinar", flag: "rs", symbol: "Дин." },
    { code: "RUB", name: "Russian Ruble", flag: "ru", symbol: "₽" },
    { code: "RWF", name: "Rwandan Franc", flag: "rw", symbol: "RWF" },
    { code: "SAR", name: "Saudi Riyal", flag: "sa", symbol: "﷼" },
    { code: "SBD", name: "Solomon Islands Dollar", flag: "sb", symbol: "$" },
    { code: "SCR", name: "Seychellois Rupee", flag: "sc", symbol: "₨" },
    { code: "SDG", name: "Sudanese Pound", flag: "sd", symbol: "ج.س." },
    { code: "SEK", name: "Swedish Krona", flag: "se", symbol: "kr" },
    { code: "SGD", name: "Singapore Dollar", flag: "sg", symbol: "S$" },
    { code: "SHP", name: "Saint Helena Pound", flag: "sh", symbol: "£" },
    { code: "SLL", name: "Sierra Leonean Leone", flag: "sl", symbol: "Le" },
    { code: "SOS", name: "Somali Shilling", flag: "so", symbol: "S" },
    { code: "SRD", name: "Surinamese Dollar", flag: "sr", symbol: "$" },
    { code: "SSP", name: "South Sudanese Pound", flag: "ss", symbol: "£" },
    { code: "STN", name: "São Tomé and Príncipe Dobra", flag: "st", symbol: "Db" },
    { code: "SVC", name: "Salvadoran Colón", flag: "sv", symbol: "₡" },
    { code: "SYP", name: "Syrian Pound", flag: "sy", symbol: "£" },
    { code: "SZL", name: "Swazi Lilangeni", flag: "sz", symbol: "L" },
    { code: "THB", name: "Thai Baht", flag: "th", symbol: "฿" },
    { code: "TJS", name: "Tajikistani Somoni", flag: "tj", symbol: "SM" },
    { code: "TMT", name: "Turkmenistani Manat", flag: "tm", symbol: "T" },
    { code: "TND", name: "Tunisian Dinar", flag: "tn", symbol: "د.ت" },
    { code: "TOP", name: "Tongan Paʻanga", flag: "to", symbol: "T$" },
    { code: "TRY", name: "Turkish Lira", flag: "tr", symbol: "₺" },
    { code: "TTD", name: "Trinidad and Tobago Dollar", flag: "tt", symbol: "TT$" },
    { code: "TWD", name: "New Taiwan Dollar", flag: "tw", symbol: "NT$" },
    { code: "TZS", name: "Tanzanian Shilling", flag: "tz", symbol: "TSh" },
    { code: "UAH", name: "Ukrainian Hryvnia", flag: "ua", symbol: "₴" },
    { code: "UGX", name: "Uganda Shilling", flag: "ug", symbol: "USh" },
    { code: "UYU", name: "Uruguayan Peso", flag: "uy", symbol: "$U" },
    { code: "UZS", name: "Uzbekistani Som", flag: "uz", symbol: "so'm" },
    { code: "VES", name: "Venezuelan Bolívar", flag: "ve", symbol: "Bs." },
    { code: "VND", name: "Vietnamese Dong", flag: "vn", symbol: "₫" },
    { code: "VUV", name: "Vanuatu Vatu", flag: "vu", symbol: "VT" },
    { code: "WST", name: "Samoan Tālā", flag: "ws", symbol: "WS$" },
    { code: "XAF", name: "Central African CFA franc", flag: "cm", symbol: "FCFA" },
    { code: "XCD", name: "East Caribbean Dollar", flag: "ag", symbol: "EC$" },
    { code: "XOF", name: "West African CFA Franc", flag: "sn", symbol: "CFA" },
    { code: "XPF", name: "CFP Franc", flag: "pf", symbol: "₣" },
    { code: "YER", name: "Yemeni Rial", flag: "ye", symbol: "﷼" },
    { code: "ZAR", name: "South African Rand", flag: "za", symbol: "R" },
    { code: "ZMW", name: "Zambian Kwacha", flag: "zm", symbol: "ZK" }
],
}
  export default countriesData;